### ISSUE TITLE
Error: name 'images' in not defined

### ISSUE THREAD

**Issue by hetvipatel11** [adumrewal/SIFTImageSimilarity#2]
![image](https://user-images.githubusercontent.com/56166476/160375690-349ab8f7-4644-48bf-a42f-d2394df4953b.png)

**Comment by amold96** [comment]
The purpose of cell (54) is to convert loaded color images into gray_scale (only if one has already loaded color images using some other code).

If you look at the jupyter notebook in the repo, this (cell 54) is a commented code as you don't need to perform color conversion operation, because the images are already loaded in gray-scale (cell 53).
In the notebook, this was done using: `cv2.imread(imagePath,0)` in the previous cell (53).

I hope this helps clarify your doubt. I'll add some comment around that cell so that it becomes self-explanatory for all.

PS. it would be helpful if you could rename the issue to `Error: name 'images' in not defined` or something in those lines as it gives the users a brief idea about the issue and helps them search among other issues easily.
