### ISSUE TITLE
Calculate result

### ISSUE THREAD

**Issue by vedankshah** [adumrewal/SIFTImageSimilarity#3]
Hey!! I am facing an error over here,
![image](https://user-images.githubusercontent.com/102765087/161145182-eb938bcb-9af1-47dd-85cb-f70f16691107.png)

**Comment by glasslucas00** [comment]
me too

**Comment by salsquared** [comment]
Same

**Comment by amold96** [comment]
Fixed with the latest push and updated code to utilise latest library methods. Also added a requirements.txt and setup script to ensure all users are on the same library versions.

PS. If you find any issues and are able to solve it, feel free to either raise a PR or create an issue and publish its solution there too. :)

**Comment by adumrewal** [comment]
Closing the issue as it is resolved now.
