### ISSUE TITLE
I'd like to ask you a question

### ISSUE THREAD

**Issue by yangmaoshaonian** [adumrewal/SIFTImageSimilarity#5]
The article says that the code has been tuned, I want to know in which aspect?

**Comment by adumrewal** [comment]
The cut-off's used in BFMatcher [`calculateMatches`] function and the overall cut-off for classifying an image are the two main aspects of tuning.
BFMatcher cut-off: 0.7 [`m.distance < 0.7*n.distance:`]
Classification cut-off: 1.0

Another implicit aspect is the use of BFMatcher instead of other available matchers.

I hope that answers your question.
